name: United Glory News ‚Üí Discord

on:
  push:
    paths:
      - "news/**"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Embed Notification
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "content": "@everyone",
            "embeds": [
              {
                "title": "üì¢ United Glory ¬∑ News",
                "description": "**Nuevo comunicado oficial disponible.**\n\nüëâüèª [Ver United Glory News](https://ugesport.icu/news/)",
                "color": 5793266,
                "footer": {
                  "text": "United Glory"
                },
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
              }
            ]
          }' \
          https://discord.&com/api/webhooks/1446209741461131506/wUa-IYbAso9PPrzXBb_C5-e5gmFd8qQNpDNfgwDVGcSzJva_whwFpI5lfb2pD0aDRFgo